version: '3.8'

services:
  auth:
    container_name: auth
    image: auth-server:latest
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - AUTH_PORT=8080
      - AUTH_HOST=0.0.0.0
      - LOG_LEVEL=DEBUG
      - APP_ENV=dev
      - MIGRATIONS_DIR=./migrations/postgres
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${DB_TIMEZONE}

    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:

